source 'https://rubygems.org'

gem 'sinatra'
gem 'rake'
gem 'test-unit'
gem 'selenium-webdriver'
gem 'pg'
gem 'mail'
gem 'google-api-client', '~> 0.9', require: 'google/apis/calendar_v3'
gem 'minitest'